fieldnames = [
    "gender",
    "title",
    "first",
    "last",
    "street_number",
    "street_name",
    "city",
    "state",
    "country",
    "postcode",
    "latitude",
    "longitude",
    "timezone_offset",
    "timezone_description",
    "email",
    "uuid",
    "username",
    "password",
    "salt",
    "md5",
    "sha1",
    "sha256",
    "dob_date",
    "dob_age",
    "registered_date",
    "phone",
    "cell",
    "id_name",
    "id_value",
    "picture_large",
    "picture_medium",
    "picture_thumbnail",
    "nationality",
]

person_data = {
    "gender": person["gender"],
    "title": person["name"]["title"],
    "first": person["name"]["first"],
    "last": person["name"]["last"],
    "street_number": person["location"]["street"]["number"],
    "street_name": person["location"]["street"]["name"],
    "city": person["location"]["city"],
    "state": person["location"]["state"],
    "country": person["location"]["country"],
    "postcode": person["location"]["postcode"],
    "latitude": person["location"]["coordinates"]["latitude"],
    "longitude": person["location"]["coordinates"]["longitude"],
    "timezone_offset": person["location"]["timezone"]["offset"],
    "timezone_description": person["location"]["timezone"]["description"],
    "email": person["email"],
    "uuid": person["login"]["uuid"],
    "username": person["login"]["username"],
    "password": person["login"]["password"],
    "salt": person["login"]["salt"],
    "md5": person["login"]["md5"],
    "sha1": person["login"]["sha1"],
    "sha256": person["login"]["sha256"],
    "dob_date": person["dob"]["date"],
    "dob_age": person["dob"]["age"],
    "registered_date": person["registered"]["date"],
    "phone": person["phone"],
    "cell": person["cell"],
    "id_name": person["id"]["name"],
    "id_value": person["id"]["value"],
    "picture_large": person["picture"]["large"],
    "picture_medium": person["picture"]["medium"],
    "picture_thumbnail": person["picture"]["thumbnail"],
    "nationality": person["nat"],
}
